### ISSUE TITLE
Handle Completable & Maybe..

### ISSUE THREAD

**Issue by aesteve** [FroMage/redpipe#41]
Hello,

At the moment, the classes :
* ` Completable` 
* ` Maybe`

Are not handled.

I think they are mappable :
* Completable could be mapped to HTTP 204 when it's completed. That's typically the case of a CRUD `DELETE` 
* `Maybe<T>` could be mapped to 200 if present, as long as `T` is marshallable, and 404 if it emits no value. Typical use case `findByCriteria(...)`

**Comment by FroMage** [comment]
I agree with `Completable` because 204 is indeed used to indicate success with no content.

I think I agree with `Maybe` and 404 if `null` too. It doesn't feel so obvious to me, because I'm not sure if it's always obvious that the 404 will be a result of a missing entity as pointed to by the requester, or an internal step that went missing that may not directly be related to the entity. But I think I agree because on the surface, it feels reasonable to justify it.
